project_id = "pzqrqsqggvawbbhgpbbx"

[functions.admin-auth]
verify_jwt = false

[functions.newsletter-subscribe]
verify_jwt = false

[functions.upload-product-image]
verify_jwt = false

[functions.admin-data]
verify_jwt = false